// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetWatch.SqlDbContext;

#nullable disable

namespace NetWatch.SqlDbContext.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20251203142510_FirstVersion")]
    partial class FirstVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetWatch.Model.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertLevel")
                        .HasColumnType("int");

                    b.Property<int>("AlertType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("NetWatch.Model.DeviceScanHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OpenPortsSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<Guid>("ScanSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScanTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusAtScan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ScanSessionId");

                    b.HasIndex("ScanTimestamp");

                    b.ToTable("DeviceScanHistories");
                });

            modelBuilder.Entity("NetWatch.Model.NetworkDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("MACAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenPorts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.HasIndex("MACAddress")
                        .IsUnique()
                        .HasFilter("[MACAddress] IS NOT NULL");

                    b.ToTable("NetworkDevices");
                });

            modelBuilder.Entity("NetWatch.Model.NetworkScanSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DevicesFoundCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPRangeScanned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NetworkScanSessions");
                });

            modelBuilder.Entity("NetWatch.Model.Alert", b =>
                {
                    b.HasOne("NetWatch.Model.NetworkDevice", "Device")
                        .WithMany("Alerts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("NetWatch.Model.DeviceScanHistory", b =>
                {
                    b.HasOne("NetWatch.Model.NetworkDevice", "Device")
                        .WithMany("ScanHistory")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetWatch.Model.NetworkScanSession", "ScanSession")
                        .WithMany("DeviceScanHistories")
                        .HasForeignKey("ScanSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("ScanSession");
                });

            modelBuilder.Entity("NetWatch.Model.NetworkDevice", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ScanHistory");
                });

            modelBuilder.Entity("NetWatch.Model.NetworkScanSession", b =>
                {
                    b.Navigation("DeviceScanHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
